In [12]:
import pandas as pd
import snowflake.connector
import json
import re

In [5]:
conn = snowflake.connector.connect(
    account="VSB79059-HJB86910",
    user="TYLER.HAAS@INNOVATION.CA.GOV",
    authenticator="externalbrowser",
    role="TRANSFORMER_ENGCA_DEV",
)

cur = conn.cursor()
cur.execute("""
    SELECT
        *
    FROM ANALYTICS_ENGCA_PRD.GOVOCAL.GOVOCAL_AI_SURVEY_RESPONDENTS s
    WHERE PUBLICATION_STATUS = 'published'
""")

df = cur.fetch_pandas_all()
df.reset_index(names="temp_id", inplace=True)

In [6]:
df.head()

,temp_id,SURVEY_RESPONDENT_ID,SURVEY_ID,AGE,GENDER_ARRAY,GENDER_CATEGORY,RACE_ETHNICITY_ARRAY,RACE_ETHNICITY_CATEGORY,USER_STATUS,PUBLICATION_STATUS,...,ROLE_AT_WORK,COUNTY,REGION,FIELD_OF_WORK,ECONOMIC_IMPACT_EXPECTATION,GOVERNMENT_ACTION_SUGGESTION,PERSONAL_AI_IMPACT,AVAILABILITY_FOR_DISCUSSION,FIELDS_COMPLETED_COUNT,_LOADED_AT
0,0,44296481-115b-41de-8f2a-feffefc24e46,5e1d74ff-9414-4ac5-865b-bde8aa02798d,Over 65,"[\n ""Man""\n]",Man (only),None,None,active,published,...,I don't currently work,Sonoma County,Far North / North Coast,Legal,The production of physical products should bec...,Basically get out of the way. Government shoul...,"Being retired, not much impact.",Maybe,10,2026-05-21 11:15:40.803488-07:00
1,1,b42ca0a9-9ee9-4a07-ad5c-ee03b3daefd9,2db00d1d-1299-4760-95ff-2b5b7850a5a7,25-44,"[\n ""I don't want to say""\n]",I don't want to say (only),None,None,active,published,...,I don't want to say,Kern County,Central Valley,I don't want to say,None,None,None,No,7,2026-05-21 11:15:40.803488-07:00
2,2,2242ff96-c6a1-4669-8309-93eaa4a2fa09,b78cbf7d-a508-4812-ba39-d0fd060d06a9,None,None,None,None,None,active,published,...,"Contractor, freelancer, or gig worker",Solano County,Bay Area,Utilities or waste management,Overall? They'll make it worse due to taking j...,"Do not allow AI to work, even for free.",None,No,8,2026-05-21 11:15:40.803488-07:00
3,3,e99183f9-704d-4475-bcfc-36d770b5866c,6cf926ac-34a6-48c4-8a56-fc78bac7a26a,45-64,None,None,None,None,active,published,...,Employee (non-management),Sacramento County,Sacramento Valley / Sierra Foothills,Government,None,None,None,Maybe,6,2026-05-21 11:15:40.803488-07:00
4,4,799530e7-2104-4fe6-9fed-f09b375fe034,e053ccc3-07e8-4794-b67c-944837c1113f,45-64,"[\n ""Woman""\n]",Woman (only),"[\n ""White""\n]",White (only),active,published,...,Employee (non-management),Alameda County,Bay Area,Healthcare,If things continue on their current trajectory...,I absolutely believe that government needs to ...,I am a clinical psychologist. Though I do not ...,Yes,11,2026-05-21 11:15:40.803488-07:00

In [7]:
OVERALL_AI_SENTIMENT_COLS = ["ECONOMIC_IMPACT_EXPECTATION", "PERSONAL_AI_IMPACT"]
GOVERNMENT_ACTION_SENTIMENT_COLS = ["GOVERNMENT_ACTION_SUGGESTION"]

SENTIMENT_OPTIONS = ["PRO", "ANTI", "NEUTRAL"]

## Step 2: Zero-Shot Classification

In [8]:
MODEL = "claude-4-sonnet"

OVERALL_SYSTEM_PROMPT = """
You are classifying California residents' survey responses about AI.
Classify the respondent's policy position and attitude toward AI as a technology — not the emotional tone of their writing.

PRO: The respondent views AI as broadly beneficial and supports its development, adoption, or expansion.
ANTI: The respondent views AI as broadly harmful and opposes its development, adoption, or expansion.
NEUTRAL: The respondent is ambivalent, holds mixed views, or does not express a clear directional stance.

Respond with JSON only, no markdown: {"label": "pro|anti|neutral", "rationale": "one sentence"}
""".strip()

GOVERNMENT_SYSTEM_PROMPT = """
You are classifying California residents' survey responses about AI governance.
Classify the respondent's policy position on government action regarding AI — not the emotional tone of their writing.

PRO: The respondent supports active government involvement (regulation, oversight, restrictions, public investment, or standards-setting).
ANTI: The respondent opposes government involvement and prefers a market-driven or hands-off approach.
NEUTRAL: The respondent is ambivalent, proposes a balanced approach, or does not express a clear directional stance.

Respond with JSON only, no markdown: {"label": "pro|anti|neutral", "rationale": "one sentence"}
""".strip()

In [9]:
def esc(s):
    # Escape for safe embedding in a Snowflake SQL string literal
    return s.replace("'", "''").replace("\n", " ").replace("\r", "")

sql = f"""
SELECT
    SURVEY_RESPONDENT_ID,
    CASE
        WHEN COALESCE(ECONOMIC_IMPACT_EXPECTATION, '') != ''
          OR COALESCE(PERSONAL_AI_IMPACT, '') != ''
        THEN SNOWFLAKE.CORTEX.COMPLETE(
            '{MODEL}',
            ARRAY_CONSTRUCT(
                OBJECT_CONSTRUCT('role', 'system', 'content', '{esc(OVERALL_SYSTEM_PROMPT)}'),
                OBJECT_CONSTRUCT('role', 'user', 'content',
                    CONCAT(
                        'Economic impact: ', COALESCE(ECONOMIC_IMPACT_EXPECTATION, '(none)'),
                        ' | Personal AI impact: ', COALESCE(PERSONAL_AI_IMPACT, '(none)')
                    )
                )
            ),
            OBJECT_CONSTRUCT('temperature', 0, 'max_tokens', 150)
        )
    END AS OVERALL_RAW,
    CASE
        WHEN COALESCE(GOVERNMENT_ACTION_SUGGESTION, '') != ''
        THEN SNOWFLAKE.CORTEX.COMPLETE(
            '{MODEL}',
            ARRAY_CONSTRUCT(
                OBJECT_CONSTRUCT('role', 'system', 'content', '{esc(GOVERNMENT_SYSTEM_PROMPT)}'),
                OBJECT_CONSTRUCT('role', 'user', 'content', COALESCE(GOVERNMENT_ACTION_SUGGESTION, ''))
            ),
            OBJECT_CONSTRUCT('temperature', 0, 'max_tokens', 150)
        )
    END AS GOVERNMENT_RAW
FROM ANALYTICS_ENGCA_PRD.GOVOCAL.GOVOCAL_AI_SURVEY_RESPONDENTS
WHERE PUBLICATION_STATUS = 'published'
"""

cur = conn.cursor()
cur.execute(sql)
raw_df = cur.fetch_pandas_all()

In [13]:
raw_df.head()

,SURVEY_RESPONDENT_ID,OVERALL_RAW,GOVERNMENT_RAW,overall_parsed,government_parsed
0,44296481-115b-41de-8f2a-feffefc24e46,"{\n ""choices"": [\n {\n ""messages"": ""{...","{\n ""choices"": [\n {\n ""messages"": ""{...","{'label': 'error', 'rationale': 'name 'json' i...","{'label': 'error', 'rationale': 'name 'json' i..."
1,b42ca0a9-9ee9-4a07-ad5c-ee03b3daefd9,None,None,None,None
2,2242ff96-c6a1-4669-8309-93eaa4a2fa09,"{\n ""choices"": [\n {\n ""messages"": ""{...","{\n ""choices"": [\n {\n ""messages"": ""{...","{'label': 'error', 'rationale': 'name 'json' i...","{'label': 'error', 'rationale': 'name 'json' i..."
3,e99183f9-704d-4475-bcfc-36d770b5866c,None,None,None,None
4,799530e7-2104-4fe6-9fed-f09b375fe034,"{\n ""choices"": [\n {\n ""messages"": ""{...","{\n ""choices"": [\n {\n ""messages"": ""{...","{'label': 'error', 'rationale': 'name 'json' i...","{'label': 'error', 'rationale': 'name 'json' i..."

In [14]:
def parse_cortex_response(raw):
    if raw is None:
        return pd.Series({"label": None, "rationale": None})
    try:
        content = json.loads(raw)["choices"][0]["messages"].strip()
        content = re.sub(r"^```(?:json)?\s*", "", content).rstrip("` \n")
        result = json.loads(content)
        return pd.Series({"label": result.get("label", "error").lower(), "rationale": result.get("rationale", "")})
    except Exception as e:
        return pd.Series({"label": "error", "rationale": str(e)})

zero_shot_df = raw_df[["SURVEY_RESPONDENT_ID"]].copy()
zero_shot_df[["overall_ai_sentiment", "overall_rationale"]] = raw_df["OVERALL_RAW"].apply(parse_cortex_response)
zero_shot_df[["government_action_sentiment", "government_rationale"]] = raw_df["GOVERNMENT_RAW"].apply(parse_cortex_response)

zero_shot_df.head()

,SURVEY_RESPONDENT_ID,overall_ai_sentiment,overall_rationale,government_action_sentiment,government_rationale
0,44296481-115b-41de-8f2a-feffefc24e46,neutral,The respondent provides a balanced analysis of...,anti,The respondent advocates for minimal governmen...
1,b42ca0a9-9ee9-4a07-ad5c-ee03b3daefd9,None,None,None,None
2,2242ff96-c6a1-4669-8309-93eaa4a2fa09,anti,The respondent expresses concern that AI will ...,pro,The respondent advocates for a complete prohib...
3,e99183f9-704d-4475-bcfc-36d770b5866c,None,None,None,None
4,799530e7-2104-4fe6-9fed-f09b375fe034,anti,The respondent expresses consistent opposition...,pro,The respondent strongly advocates for extensiv...

## Zeroshot Labelling Results

In [15]:
labeled_df = df.merge(zero_shot_df, on="SURVEY_RESPONDENT_ID", how="left")

audit_cols = [
    "SURVEY_RESPONDENT_ID",
    "ECONOMIC_IMPACT_EXPECTATION", "PERSONAL_AI_IMPACT",
    "overall_ai_sentiment", "overall_rationale",
    "GOVERNMENT_ACTION_SUGGESTION",
    "government_action_sentiment", "government_rationale",
]
labeled_df[audit_cols].head(10)

,SURVEY_RESPONDENT_ID,ECONOMIC_IMPACT_EXPECTATION,PERSONAL_AI_IMPACT,overall_ai_sentiment,overall_rationale,GOVERNMENT_ACTION_SUGGESTION,government_action_sentiment,government_rationale
0,44296481-115b-41de-8f2a-feffefc24e46,The production of physical products should bec...,"Being retired, not much impact.",neutral,The respondent provides a balanced analysis of...,Basically get out of the way. Government shoul...,anti,The respondent advocates for minimal governmen...
1,b42ca0a9-9ee9-4a07-ad5c-ee03b3daefd9,None,None,None,None,None,None,None
2,2242ff96-c6a1-4669-8309-93eaa4a2fa09,Overall? They'll make it worse due to taking j...,None,anti,The respondent expresses concern that AI will ...,"Do not allow AI to work, even for free.",pro,The respondent advocates for a complete prohib...
3,e99183f9-704d-4475-bcfc-36d770b5866c,None,None,None,None,None,None,None
4,799530e7-2104-4fe6-9fed-f09b375fe034,If things continue on their current trajectory...,I am a clinical psychologist. Though I do not ...,anti,The respondent expresses consistent opposition...,I absolutely believe that government needs to ...,pro,The respondent strongly advocates for extensiv...
5,e5c54257-28c5-4285-91e8-aab9b6349dbc,AI will automate enormous portions of the econ...,AI has affected my workplace profoundly. I'm a...,anti,The respondent views AI as harmful due to its ...,California should require AI companies to cont...,pro,The respondent advocates for mandatory governm...
6,002239f4-01ca-4dc8-b0db-002ecc6665b5,Badly. It is a waste of energy/water and gener...,Increased negative attitudes toward soft skill...,anti,The respondent views AI as economically wastef...,Regulate genAI usage according to recommendati...,pro,The respondent explicitly supports government ...
7,9d785e32-8d45-4d1d-9a70-d2aa91c5d9fb,"In some cases, people are relying too much on ...",There’s good and bad if you have a technical p...,neutral,The respondent acknowledges both positive and ...,I believe in order for us to be able to streng...,neutral,The respondent expresses a general goal about ...
8,6adf4967-dd49-4f7f-ba35-8bba6ff97535,AI shifts the power dynamic from labor to capi...,"AI has not infiltrated government as much yet,...",anti,The respondent expresses clear opposition to A...,Regulate AI. Make sure models are being design...,pro,The respondent explicitly calls for AI regulat...
9,5ab5b645-0a71-4925-93ef-539bd9a8a865,Mass disruption of the workforce resulting in ...,I work in the cyber-security industry as an En...,neutral,The respondent acknowledges both negative econ...,Ensure displaced employees are able to receive...,pro,The respondent supports active government inte...

In [20]:
print(labeled_df['overall_ai_sentiment'].value_counts(normalize=True))
print("\n")
print(labeled_df['government_action_sentiment'].value_counts(normalize=True))

overall_ai_sentiment
anti       0.576786
neutral    0.265179
pro        0.158036
Name: proportion, dtype: float64


government_action_sentiment
pro        0.894981
neutral    0.060409
anti       0.044610
Name: proportion, dtype: float64

In [22]:
print(labeled_df['overall_ai_sentiment'].value_counts())
print(labeled_df['government_action_sentiment'].value_counts())

overall_ai_sentiment
anti       646
neutral    297
pro        177
Name: count, dtype: int64
government_action_sentiment
pro        963
neutral     65
anti        48
Name: count, dtype: int64

## Step 3: Exemplar Selection

In [29]:
CHUNK_SIZE = 20
PICKS_PER_CHUNK = 5
STOP_THRESHOLD = 25
FINAL_TARGET = 10


def fmt_overall_text(row):
    parts = []
    if pd.notna(row["ECONOMIC_IMPACT_EXPECTATION"]) and row["ECONOMIC_IMPACT_EXPECTATION"]:
        parts.append(f"[Economic] {row['ECONOMIC_IMPACT_EXPECTATION'].strip()}")
    if pd.notna(row["PERSONAL_AI_IMPACT"]) and row["PERSONAL_AI_IMPACT"]:
        parts.append(f"[Personal] {row['PERSONAL_AI_IMPACT'].strip()}")
    return "\n".join(parts)


labeled_df["overall_text"] = labeled_df.apply(fmt_overall_text, axis=1)
labeled_df["government_text"] = labeled_df["GOVERNMENT_ACTION_SUGGESTION"].fillna("").str.strip()

In [30]:
EXEMPLAR_SYSTEM_PROMPT = """You are selecting canonical examples of a labeled survey response for use as few-shot classification examples.

The responses below are all labeled "{label}" for the category "{category}". Select the {n} best examples.

Prefer:
- Substantive over short or obvious: pick responses that make specific arguments or show a clear policy position
- Diverse: if possible, cover different angles of the "{label}" position rather than picking responses that repeat the same point

Return ONLY a JSON array of the response numbers you selected. Example: [2, 7, 14]"""


def cortex_complete(messages, max_tokens=150):
    # Parameterized binding lets the connector handle escaping — avoids Snowflake
    # interpreting \n in json.dumps output as a literal newline before PARSE_JSON sees it.
    messages_json = json.dumps(messages)
    sql = """SELECT SNOWFLAKE.CORTEX.COMPLETE(
        %s,
        PARSE_JSON(%s),
        OBJECT_CONSTRUCT('temperature', 0, 'max_tokens', %s)
    )"""
    cur = conn.cursor()
    cur.execute(sql, [MODEL, messages_json, max_tokens])
    raw = cur.fetchone()[0]
    content = json.loads(raw)["choices"][0]["messages"].strip()
    return re.sub(r"^```(?:json)?\s*", "", content).rstrip("` \n")


def select_from_chunk(texts, label, category, n_picks):
    numbered = "\n\n".join(f"[{i+1}] {t}" for i, t in enumerate(texts))
    system = EXEMPLAR_SYSTEM_PROMPT.format(label=label, category=category, n=n_picks)
    content = cortex_complete([
        {"role": "system", "content": system},
        {"role": "user", "content": numbered},
    ])
    try:
        picks = json.loads(content)
        return [p - 1 for p in picks if isinstance(p, int) and 1 <= p <= len(texts)]
    except Exception:
        print(f"  Warning: could not parse picks response: {content[:100]}")
        return list(range(min(n_picks, len(texts))))


def reduce_to_exemplars(texts, label, category):
    pool = list(range(len(texts)))

    while len(pool) > STOP_THRESHOLD:
        next_pool = []
        pool_texts = [texts[i] for i in pool]
        for start in range(0, len(pool_texts), CHUNK_SIZE):
            chunk = pool_texts[start:start + CHUNK_SIZE]
            picks = select_from_chunk(chunk, label, category, min(PICKS_PER_CHUNK, len(chunk)))
            next_pool.extend(pool[start + p] for p in picks)
        pool = next_pool
        print(f"  [{category} / {label}] pool → {len(pool)}")

    if len(pool) > FINAL_TARGET:
        pool_texts = [texts[i] for i in pool]
        picks = select_from_chunk(pool_texts, label, category, FINAL_TARGET)
        pool = [pool[p] for p in picks]

    return pool

In [31]:
CATEGORY_TEXT_COLS = {
    "overall_ai_sentiment": "overall_text",
    "government_action_sentiment": "government_text",
}

exemplar_dfs = {}

for category, text_col in CATEGORY_TEXT_COLS.items():
    exemplar_dfs[category] = {}
    for label in [s.lower() for s in SENTIMENT_OPTIONS]:
        mask = (labeled_df[category] == label) & (labeled_df[text_col] != "")
        subset = labeled_df[mask].copy()
        print(f"\n{category} / {label}: {len(subset)} responses")
        selected = reduce_to_exemplars(subset[text_col].tolist(), label, category)
        exemplar_dfs[category][label] = subset.iloc[selected].reset_index(drop=True)
        print(f"  → {len(selected)} exemplars selected")

print("\nDone!")

overall_ai_sentiment / pro: 177 responses
  [overall_ai_sentiment / pro] pool → 45
  [overall_ai_sentiment / pro] pool → 15
  → 10 exemplars selected

overall_ai_sentiment / anti: 646 responses
  [overall_ai_sentiment / anti] pool → 165
  [overall_ai_sentiment / anti] pool → 45
  [overall_ai_sentiment / anti] pool → 15
  → 10 exemplars selected

overall_ai_sentiment / neutral: 297 responses
  [overall_ai_sentiment / neutral] pool → 75
  [overall_ai_sentiment / neutral] pool → 20
  → 10 exemplars selected

government_action_sentiment / pro: 963 responses
  [government_action_sentiment / pro] pool → 243
  [government_action_sentiment / pro] pool → 63
  [government_action_sentiment / pro] pool → 18
  → 10 exemplars selected

government_action_sentiment / anti: 48 responses
  [government_action_sentiment / anti] pool → 15
  → 10 exemplars selected

government_action_sentiment / neutral: 65 responses
  [government_action_sentiment / neutral] pool → 20
  → 10 exemplars selected

Done!

In [32]:
for category, text_col in CATEGORY_TEXT_COLS.items():
    print(f"\n{'='*70}")
    print(f"CATEGORY: {category.upper()}")
    for label in [s.lower() for s in SENTIMENT_OPTIONS]:
        print(f"\n{'─'*40}\n  LABEL: {label}\n{'─'*40}")
        for rank, row in enumerate(exemplar_dfs[category][label].itertuples(), 1):
            text = getattr(row, text_col)
            print(f"\n[{rank}] {text[:600]}{'...' if len(text) > 600 else ''}")

======================================================================
CATEGORY: OVERALL_AI_SENTIMENT

────────────────────────────────────────
  LABEL: pro
────────────────────────────────────────

[1] [Economic] AI is likely to have a major impact on the economy by increasing productivity, changing how work is performed, and creating new industries, tools, and business models. In many sectors, AI can help organizations process information faster, automate repetitive tasks, improve customer service, reduce administrative burden, and support better decision-making.

For government and public services, AI could improve permitting, benefits administration, public inquiries, fraud detection, cybersecurity, emergency response, and data analysis. For businesses, it may reduce costs, speed up produ...

[2] [Economic] AI is a disruptive technology. People and jobs will be displaced. The more useful question is whether displacement is the same thing as replacement — and history suggests it isn't.

When photography devastated the market for portrait painters, the arguments against it were remarkably similar to those made against AI today. And yet without the camera forcing painters off the turf of illusion-making, you don't get Van Gogh, Picasso, or Pollock, nor the convenience of a camera on your phone.

Photography didn't replace artists. It changed what they did, while democratizing the producti...

[3] [Economic] AI is poised to be one of the most powerful drivers of economic growth and prosperity the world has ever seen. By automating repetitive tasks and supercharging productivity across industries — from manufacturing and healthcare to finance and agriculture — AI enables businesses to operate more efficiently, reduce costs, and deliver better products and services to more people. It opens the door to entirely new industries and job categories that didn't exist before, much like the internet revolution did a generation ago. Small businesses and entrepreneurs gain access to tools and capab...

[4] [Economic] Just like all new waves of technology, AI will allow and require workers to move up a level of their contribution to their work product. This will be more difficult for some than for others. I've been in the software and data industry since 1977. One example is the accelerating use of spreadsheets on personal computers in the early 80s. Over time, there weren't fewer people focused on financial modeling. Instead moving from paper, pencils, and calculators allowed them to create many more versions of scenarios resulting in higher quality decisions. A second example is with the advent...

[5] [Economic] I predict AI will disrupt current business models for knowledge work. Per-hour and/or per-seat billing won't make sense when a well-tuned AI can quickly perform the work of a whole team of people. Value will need to be measured and compensated in some other way.

Knowledge work will still need humans to oversee accuracy and delivery. But the way we pay each other for that work will totally change. I foresee a lot of status quo companies dying, and a lot of new companies rising up.

I'm not worried about AI putting everyone out of work. We've heard that about every new technology si...

[6] [Economic] AI is likely to be a major driver of productivity growth across industries. It will enable organizations to automate routine work, reduce operational costs, and innovate more quickly. At the same time, it will shift the types of skills that are in demand, increasing the value of technical literacy, adaptability, and the ability to work alongside AI systems.
While AI may displace some roles that rely heavily on repetitive tasks, it will also create new opportunities in areas such as system design, oversight, integration, and AI-enabled services. The overall economic impact will depen...

[7] [Economic] I think it has the potential to flip the economy upside down.

But I don't see that as a bad thing. I think if it takes over the workforce - which is also not a bad thing, btw - it will force corporations and the government (state & federal) to implement Universal Basic Income.

Now that I have been receiving Social Security for a number of years, it makes me sad to think that if we had been getting SS or something like it when we became the age of an adult, how different the world would be. How much work could I have done? Even though I do not receive much, it's enough that I can...

[8] [Economic] How and how much AI will impact the economy depend on a lot of factors which are far from decided at this point. But I believe that AI could relieve a huge amount of human toil an unlock new capacity if harnessed constructively, and it if is regulated, governed and powered responsibly.
[Personal] AI has impacted many aspects of my current, past, and in my opinion all of my future jobs. There are massive gains to productivity and capacity that are possible, and also major security questions and vulnerabilities that still need to be addressed. There is one clear leader in the AI space...

[9] [Economic] AI can drive some businesses forward and leave others in the dust. It will accelerate growth for the large businesses who control it, and the small businesses who use it profitably. I expect a similar pattern will emerge with historical leaps in technology—the rich will get richer, the poor will get poorer as a result of renewed profit motives and an apathetic political class. But I don’t believe this is the path we will take. I believe California will demonstrate a different path—one that’s centered around helping the most humans, not the least.
[Personal] We are using it all day, ...

[10] [Personal] Yes, very positively - I can do more, learn more, and produce more.  I attribute AI-led upskilling to my recent promotion.

────────────────────────────────────────
  LABEL: anti
────────────────────────────────────────

[1] [Economic] If things continue on their current trajectory without regulatory intervention, I expect mass layoffs in particular industries that are highly concentrated in California, especially software development and entertainment. I worry that this could be devastating for our economy. I also worry about environmental impact of mass AI adoption, including pollution and excessive energy consumption from data centers, with obvious downstream economic impacts from accelerated climate change and worsening health outcomes. I expect that AI will worsen inequality along lines of gender, race, and s...

[2] [Economic] When people lose jobs, they stop spending. Without liquid expendable income, how will we buy the goods and services of companies that are firing individuals to replace with AI are trying to sell to us? When we can't afford the supply, the demand goes down. No. One. Wins. I can tell you with utmost confidence that I have decided not to have children BECAUSE of the way the world is going - from the environmental impacts of AI to the fact that my child would not be able to get a job. I can barely get one as that are being given to AI instead. Unregulated AI will demolish what is remain...

[3] [Economic] GenAI's sole significant achievement is in drastically reducing payroll, which -  on a large scale - should be recognized by intelligent people as a bad thing. It is is a wildly unprofitable technology being used to prop up an economy in steep decline. So, on top of being used as an excuse to lay off wide swaths of people in areas they can no longer afford to live, the entire industry is an enormous bubble just waiting to pop.

Of course, if GenAI weren't this blatant scam, we'd be in even more trouble. Clearly corporations are salivating at the idea of unemploying as many people as...

[4] [Economic] There's no upside to it. My wife works at the largest entertainment corporation in the world, in their AI department. This thing is slashing and burning jobs as I type this. For all those jobs, those are taxpayers, parents, consumers, and the trickle out effect of production leaving Los Angeles has already been a runaway train, Ai just poured gasoline on it,  our representatives cannot react fast eough, don't understand the peril, or at worst laissez faire about it. Hollywood is the birthplace of film, of dreamers and vagabonds, and now it's being run by Silicon Valley who stole all...

[5] [Economic] AI is currently being used to extract expertise and wealth from the white collar middle class to the ownership class. *All* current commercial AI models were trained using data scraped from the internet without consent, credit, compensation, or transparency -  data that the AI developers do not own, and have made minimal efforts to pay for.

Left unchecked, the tech industry will do to California's creative industry what it did to taxi drivers with ridesharing apps like Uber and the hotel industry with vacation rentals like Airbnb -  it will infiltrate the industry, offer a more co...

[6] [Economic] I think it's going to catastrophic if more is not done to curtail it. It's trying to reach into every aspect of society, and when it fails because it's not sustainable, ethical, or effective at what it promises to do, we will have to bear the fallout. In particular I am very concerned about AI being used in education, and how this will negatively impact the workforce in the future. We need a well educated citizenry of people who can think critically and independently in order to have people who will create value and profit. At this rate, we will be in a dire situation that may take ...

[7] [Economic] This could have huge ramifications for the overall economy both state and national. Money that would have gone to jobs, products, and taxes are instead being spent on speculation of a software that still despite billions of dollars of investment does not have a working prototype. Reading expert papers, as long as Generative AI is based on LLMs, it will always hallucinate; it will take a new type of logic replacing LLMs for this to ever be safe and reliable. What this means is, we are seeing massive unemployment across all sectors as companies spend money on AI speculation instead of...

[8] [Economic] Negatively, as I already see it happening at every level, in every field and with knock-on effects. As I said above, specifically, the entertainment/film industry, which California is famous for, has contracted so badly due to image, voice and music generation competing directly with artists and craftspeople in their fields. It has contributed to the decimation of film production in California directly.
[Personal] GenAI has heavily impacted my job. I work in arts/entertainment as a concept artist, and have witnessed my industry all but die on the vine as studios and companies rush t...

[9] [Economic] Complete destruction of the middle and working classes. The ruination of the capacity to think deeply, distill information, and create. Utter destruction of our environment. An information environment where no one can trust anything. It will be the end of us. So many people I know in the arts (and tech) are now out of work thanks to AI. These are high earners who have now been looking for work for over a year. Everything is precarious. We are terrified.
[Personal] My copywriting work has been obliterated by AI. On the books side, I am part of a class-action lawsuit after the AI comp...

[10] [Economic] I expect generative AI as popularly used right now to be a bubble.  While some infrastructural products may go on to be useful, the externalities driven by generative AI in combination with the limited utility of AI in replicating cognitive effort make AI more of a liability than a cost-savings mechanism in the medium term.  Once the short-term returns for reducing staff costs by using AI have reached a plateau, competitive advantage in the marketplace will shift to firms that focus on hiring talent and developing skills.
[Personal] AI has made work processes more duplicative at the...

────────────────────────────────────────
  LABEL: neutral
────────────────────────────────────────

[1] [Personal] I work in climate and environmental data science. A lot of what we call AI is essentially just advanced data analysis, like the kind of weather modeling and forecasting we've been doing for years. The latest machine learning and computer vision tools can make data easier to share and publish, which in turn makes it possible for more people to use data and generate new insights. The problem is the hype and the error rates around frontier models, especially chatbots. Most public data, including lots of California state data, is not AI-ready. LLMs often substitute incorrect statements ...

[2] [Economic] Like all leading edge research projects, the breakthroughs will be intermittent, and the benefits will not be evenly distributed. In the near term, these benefits will be overshadowed by the burst of a bubble as major companies which have heavily overinvested, particularly in LLMs, absorb significant losses, and many of them will cut their workforces to compensate, further damaging the economy. Additionally, companies whose management approach these as replacement for human labor rather than what they more closely resemble — newer, sometimes better software tools — will also do sign...

[3] [Economic] AI has been reshaping California’s economy in many ways. It may improve productivity and create new industries, but it has also been disrupting many jobs, especially in technology, media, and administrative work. I am concerned that rapid investment in AI, combined with limited regulation, could create economic instability similar to previous tech bubbles. AI-generated content is already affecting journalism, entertainment, education, and social media by increasing misinformation and low-quality automated content at scale. These impacts can be especially harmful to children and publ...

[4] [Economic] It will be very disruptive.
Benefits:
1) It could reduce healthcare costs if used carefully to evaluate data in fields such as radiology and dermatology.  It could reduce costs if used to evaluate epidemiology data and develop cost effective standards of care.
2) AI could be very useful in any field that requires data pattern recognition.
Harms:
1) It might reduce human beings to just data points.
2) It could be used as the ultimate method to manipulate/control humans.
3) AI mistakes would be very difficult to correct and could create Kafkaesque problems for individuals (similar t...

[5] [Economic] Significant displacement in routine cognitive work over the next five to ten years: tier 1 support, junior development, content generation, entry-level analysis. Productivity gains will concentrate in companies with strong technical foundations, widening the gap between leaders and laggards. New roles will emerge in AI orchestration and governance but will not absorb displaced workers one-for-one. The real risk is not mass unemployment but a hollowed career ladder. If AI does the work juniors used to do, where do tomorrow's seniors come from? Compute and energy demand will reshape i...

[6] [Economic] AI is primarily functioning as a catalyst for productivity that simultaneously threatens to deepen structural inequality. By automating routine cognitive tasks, it allows for a significant leap in GDP and corporate efficiency, yet these gains are often concentrated within a small tier of tech dominant firms and high capital investors rather than being distributed through traditional wage growth. While the labor market hasn't seen the mass unemployment once feared, it is undergoing a re-skilling squeeze where the demand for specialized technical and infrastructure roles is skyrocketi...

[7] [Economic] It will wash out as a push in my opinion. The many benefits of it will be wiped out by the negative impacts. On the positive side it increases access to information and creative options to small businesses and individuals which could lead to more businesses opening, it can increase task efficiency which leads to cost savings for all businesses as they can use the saved time for other tasks and cut unneeded staff or hire lesser qualified staff. On the negative economical side, it will take away many higher level positions in organizations so there may be an exodus of highly educated/...

[8] [Economic] I don't expect AI to actually change much about the day-to-day reality/workloads of most workers, but I expect those in management/supervisory positions to overestimate the impact of AI and the difference it will make in workloads. Those projections will then be used to cut labor costs. This will inevitably lead to mass layoffs, unemployment, and underemployment, but also reduced productivity (and by extension, profits) for the companies that initiated those labor cuts once the reality sinks in of how unequipped AI is to "take over" human roles. Like most technology, AI as it is req...

[9] [Economic] The main economic effect will be continuing to transfer the wealth and wage distribution in a regressive direction as those with money and resources continue to consolidate their share of the wealth.  The technology itself has many positive economic applications.  However, the current lack of a sufficient regulatory structure leaves many perverse incentives in place that will continue to encourage budget and profit oriented organizations to cut as many human personnel as possible.  Employing human employees is very expense, I understand that.  The alternative to paying the high cost...

[10] [Economic] The big fear I have is less to do with displacement, and more to do with the fact that the bottleneck to increased efficiency with AI is the capacity of human verification. Businesses will be pressured to reduce human capital and allow more and more unverified AI-output be deployed - injecting unpriced risk into the economy. And as there are less and less entry-level employees there'll be fewer and fewer people gaining the expertise needed to verify AI-output, creating a vicious cycle of increasingly unverified output alongside unemployment. We've already seen how this can play out ...

======================================================================
CATEGORY: GOVERNMENT_ACTION_SENTIMENT

────────────────────────────────────────
  LABEL: pro
────────────────────────────────────────

[1] I absolutely believe that government needs to step in as a counterbalancing force to the tech companies pushing AI on all of us before it has been adequately studied and tested for safety and before there are sufficient guardrails. I know I am probably in the minority here, but I support a total moratorium on new AI products coming to market until they have gone through a regulatory process, much like new drugs have to go through the FDA. I believe that safety, particularly of children and the psychologically vulnerable, needs to be prioritized over profit. The government should employ not jus...

[2] Government should take a balanced approach and encourage responsible AI innovation while protecting workers and the public. This should include investing in workforce training and reskilling so employees can use AI effectively and move into higher-value roles as job duties change. Government should also require strong AI governance, including review for privacy, cybersecurity, bias, accessibility, transparency, and accuracy before AI tools are deployed. High-impact decisions involving benefits, employment, licensing, enforcement, or public safety should include human oversight. Labor, employee...


In [33]:
keep_cols = [
    "SURVEY_RESPONDENT_ID",
    "ECONOMIC_IMPACT_EXPECTATION", "PERSONAL_AI_IMPACT",
    "GOVERNMENT_ACTION_SUGGESTION",
    "overall_ai_sentiment", "overall_rationale",
    "government_action_sentiment", "government_rationale",
]

parts = []
for category, text_col in CATEGORY_TEXT_COLS.items():
    for label, sub_df in exemplar_dfs[category].items():
        chunk = sub_df[keep_cols].copy()
        chunk["exemplar_category"] = category
        chunk["exemplar_label"] = label
        chunk["exemplar_text"] = sub_df[text_col].values
        parts.append(chunk)

exemplars_df = pd.concat(parts, ignore_index=True)
exemplars_df.to_csv("exemplars.csv", index=False)
print(f"Saved {len(exemplars_df)} rows to exemplars.csv")